---
title: "Week 1 Notes - Course Introduction"
date: "2025-09-08"
---

## Key Concepts Learned
- Repository(repo): folders containing project files 
- Commit: snapshot work at a point
  Push: send changes to the Github cloud 
  Pull: get the latest changes from the Github cloud
- Quarto: Publishing system into professional documents
  
## Coding Techniques
- Main Header
  Section Header  
  Subsection Header
- [Quarto features learned]

## Questions & Challenges
- Not really understand what Tibbles are

## Connections to Policy
- [How this week's content applies to real policy work]

## Reflection
- [What was most interesting]
- Always clone the github repo locally on your computer (in R studio), work on the files on your local computer and when ready, push those changes to GitHub.
- Use R Projects to organize your working directory.
- You can render each quarto document separately, but before you push your website, use the terminal in R studio and type 'quarto render' to generate the whole website.

