project:
  type: website
  output-dir: docs

website:
  title: "Yiming Cao - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "Weekly Notes"
        menu: 
          - href: weekly-notes/
            text: "All Notes"
          - href: weekly-notes/week-01-notes.qmd
            text: "Week1"
          - href: weekly-notes/week-02-notes.qmd
            text: "Week2"
          - href: weekly-notes/week-03-notes.qmd
            text: "Week3"
          - href: weekly-notes/week-04-notes.qmd
            text: "Week4"
          - href: weekly-notes/week-05-notes.qmd
            text: "Week5"
      - text: "Labs"
        menu:
          - href: labs/lab_0/lab0_template.qmd
            text: "Lab 0: Dplyr Basics"
          - href: labs/lab_1/assignment1_template.qmd
            text: "Assignment 1: Census Data Exploration"
          - href: labs/lab_2/assignment2_template.qmd
            text: "Assignment 2: Spatial Analysis and Visualization"
          - href: labs/lab_3/Midterm_2025_Slides.qmd
            text: "Assignment 3: Philadelphia Housing Model"
      - text: "Assignments"
        menu:
          - href: labs/lab_3/Midterm_2025_Technical_Appendix.qmd
            text: "Assignment 3: Philadelphia Housing Model"
      
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
