project:
  type: website
  output-dir: docs

website:
  title: "Yiming Cao - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "Weekly Notes"
        menu: 
          - href: weekly-notes/
            text: "All Notes"
          - href: weekly-notes/week-01-notes.qmd
            text: "Week1"
          - href: weekly-notes/week-02-notes.qmd
            text: "Week2"
      - text: "Labs"
        menu:
          - href: labs/lab_0/lab0_template.qmd
            text: "Lab 0: Dplyr Basics"
      - text: "Assignments"
        menu:
          - href: labs/lab_0/lab0_template.qmd
            text: "Assignment1"
      
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
