{
  "hash": "8875e0d9bf4ac6c8baae823c8fb1c656",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Ming\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(scipen = 999, dplyr.summarise.inform = FALSE)\n\npkgs <- c(\n  \"tidyverse\",\"sf\",\"tigris\",\"tidycensus\",\"janitor\",\"units\",\"nngeo\",\n  \"knitr\",\"kableExtra\",\"scales\",\"ggtext\",\"glue\"\n)\ninvisible(lapply(pkgs, function(p) if (!requireNamespace(p, quietly = TRUE)) install.packages(p)))\nlapply(pkgs, library, character.only = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n [1] \"lubridate\" \"forcats\"   \"stringr\"   \"dplyr\"     \"purrr\"     \"readr\"    \n [7] \"tidyr\"     \"tibble\"    \"ggplot2\"   \"tidyverse\" \"stats\"     \"graphics\" \n[13] \"grDevices\" \"utils\"     \"datasets\"  \"methods\"   \"base\"     \n\n[[2]]\n [1] \"sf\"        \"lubridate\" \"forcats\"   \"stringr\"   \"dplyr\"     \"purrr\"    \n [7] \"readr\"     \"tidyr\"     \"tibble\"    \"ggplot2\"   \"tidyverse\" \"stats\"    \n[13] \"graphics\"  \"grDevices\" \"utils\"     \"datasets\"  \"methods\"   \"base\"     \n\n[[3]]\n [1] \"tigris\"    \"sf\"        \"lubridate\" \"forcats\"   \"stringr\"   \"dplyr\"    \n [7] \"purrr\"     \"readr\"     \"tidyr\"     \"tibble\"    \"ggplot2\"   \"tidyverse\"\n[13] \"stats\"     \"graphics\"  \"grDevices\" \"utils\"     \"datasets\"  \"methods\"  \n[19] \"base\"     \n\n[[4]]\n [1] \"tidycensus\" \"tigris\"     \"sf\"         \"lubridate\"  \"forcats\"   \n [6] \"stringr\"    \"dplyr\"      \"purrr\"      \"readr\"      \"tidyr\"     \n[11] \"tibble\"     \"ggplot2\"    \"tidyverse\"  \"stats\"      \"graphics\"  \n[16] \"grDevices\"  \"utils\"      \"datasets\"   \"methods\"    \"base\"      \n\n[[5]]\n [1] \"janitor\"    \"tidycensus\" \"tigris\"     \"sf\"         \"lubridate\" \n [6] \"forcats\"    \"stringr\"    \"dplyr\"      \"purrr\"      \"readr\"     \n[11] \"tidyr\"      \"tibble\"     \"ggplot2\"    \"tidyverse\"  \"stats\"     \n[16] \"graphics\"   \"grDevices\"  \"utils\"      \"datasets\"   \"methods\"   \n[21] \"base\"      \n\n[[6]]\n [1] \"units\"      \"janitor\"    \"tidycensus\" \"tigris\"     \"sf\"        \n [6] \"lubridate\"  \"forcats\"    \"stringr\"    \"dplyr\"      \"purrr\"     \n[11] \"readr\"      \"tidyr\"      \"tibble\"     \"ggplot2\"    \"tidyverse\" \n[16] \"stats\"      \"graphics\"   \"grDevices\"  \"utils\"      \"datasets\"  \n[21] \"methods\"    \"base\"      \n\n[[7]]\n [1] \"nngeo\"      \"units\"      \"janitor\"    \"tidycensus\" \"tigris\"    \n [6] \"sf\"         \"lubridate\"  \"forcats\"    \"stringr\"    \"dplyr\"     \n[11] \"purrr\"      \"readr\"      \"tidyr\"      \"tibble\"     \"ggplot2\"   \n[16] \"tidyverse\"  \"stats\"      \"graphics\"   \"grDevices\"  \"utils\"     \n[21] \"datasets\"   \"methods\"    \"base\"      \n\n[[8]]\n [1] \"knitr\"      \"nngeo\"      \"units\"      \"janitor\"    \"tidycensus\"\n [6] \"tigris\"     \"sf\"         \"lubridate\"  \"forcats\"    \"stringr\"   \n[11] \"dplyr\"      \"purrr\"      \"readr\"      \"tidyr\"      \"tibble\"    \n[16] \"ggplot2\"    \"tidyverse\"  \"stats\"      \"graphics\"   \"grDevices\" \n[21] \"utils\"      \"datasets\"   \"methods\"    \"base\"      \n\n[[9]]\n [1] \"kableExtra\" \"knitr\"      \"nngeo\"      \"units\"      \"janitor\"   \n [6] \"tidycensus\" \"tigris\"     \"sf\"         \"lubridate\"  \"forcats\"   \n[11] \"stringr\"    \"dplyr\"      \"purrr\"      \"readr\"      \"tidyr\"     \n[16] \"tibble\"     \"ggplot2\"    \"tidyverse\"  \"stats\"      \"graphics\"  \n[21] \"grDevices\"  \"utils\"      \"datasets\"   \"methods\"    \"base\"      \n\n[[10]]\n [1] \"scales\"     \"kableExtra\" \"knitr\"      \"nngeo\"      \"units\"     \n [6] \"janitor\"    \"tidycensus\" \"tigris\"     \"sf\"         \"lubridate\" \n[11] \"forcats\"    \"stringr\"    \"dplyr\"      \"purrr\"      \"readr\"     \n[16] \"tidyr\"      \"tibble\"     \"ggplot2\"    \"tidyverse\"  \"stats\"     \n[21] \"graphics\"   \"grDevices\"  \"utils\"      \"datasets\"   \"methods\"   \n[26] \"base\"      \n\n[[11]]\n [1] \"ggtext\"     \"scales\"     \"kableExtra\" \"knitr\"      \"nngeo\"     \n [6] \"units\"      \"janitor\"    \"tidycensus\" \"tigris\"     \"sf\"        \n[11] \"lubridate\"  \"forcats\"    \"stringr\"    \"dplyr\"      \"purrr\"     \n[16] \"readr\"      \"tidyr\"      \"tibble\"     \"ggplot2\"    \"tidyverse\" \n[21] \"stats\"      \"graphics\"   \"grDevices\"  \"utils\"      \"datasets\"  \n[26] \"methods\"    \"base\"      \n\n[[12]]\n [1] \"glue\"       \"ggtext\"     \"scales\"     \"kableExtra\" \"knitr\"     \n [6] \"nngeo\"      \"units\"      \"janitor\"    \"tidycensus\" \"tigris\"    \n[11] \"sf\"         \"lubridate\"  \"forcats\"    \"stringr\"    \"dplyr\"     \n[16] \"purrr\"      \"readr\"      \"tidyr\"      \"tibble\"     \"ggplot2\"   \n[21] \"tidyverse\"  \"stats\"      \"graphics\"   \"grDevices\"  \"utils\"     \n[26] \"datasets\"   \"methods\"    \"base\"      \n```\n\n\n:::\n\n```{.r .cell-code}\noptions(tigris_use_cache = TRUE, tigris_class = \"sf\")\n\ncrs_proj <- 26918\n\nto_miles <- function(x_meters) set_units(x_meters, \"m\") |> set_units(\"mi\") |> drop_units()\nfmt_pct  <- label_percent(accuracy = 0.1)\nfmt_num  <- label_comma(accuracy = 1)\nACS_YEAR <- 2023 \n```\n:::\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\n\n\n# Load spatial data\n\n# 1) 县界（County）\npa_counties <- counties(state = \"PA\", year = 2023, cb = TRUE) |>\n  st_as_sf() |>\n  st_transform(crs_proj) |>\n  clean_names()\n\n# 2) Census Tracts（边界）\npa_tracts <- tracts(state = \"PA\", year = 2023, cb = TRUE) |>\n  st_as_sf() |>\n  st_transform(crs_proj) |>\n  clean_names()\n\n# 3) 医院（讲义数据）：\n# 优先读取 Geopackage；若不存在，尝试读取 CSV（需含经纬度列 lon/lat 或 x/y）\nhosp_gpkg <- \"data/pa_hospitals.gpkg\"\nhosp_csv  <- \"data/pa_hospitals.csv\"\n\nhosp_geojson <- \"data/hospitals.geojson\"\n\nif (file.exists(hosp_geojson)) {\n  hospitals_raw <- read_sf(hosp_geojson)\n} else {\n  stop(\"未找到 hospitals.geojson，请确认路径与文件名正确。\")\n}\n\nhospitals <- hospitals_raw |>\n  st_transform(crs_proj) |>\n  clean_names()\n\nhospitals <- hospitals_raw |>\n  st_transform(crs_proj) |>\n  clean_names()\n\n\n# Check that all data loaded correctly\nn_hospitals <- nrow(hospitals)\nn_tracts    <- nrow(pa_tracts)\n\ncrs_info <- list(\n  counties   = st_crs(pa_counties)$input,\n  tracts     = st_crs(pa_tracts)$input,\n  hospitals  = st_crs(hospitals)$input\n)\n\nlist(\n  n_hospitals = n_hospitals,\n  n_tracts = n_tracts,\n  crs_info = crs_info\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$n_hospitals\n[1] 223\n\n$n_tracts\n[1] 3445\n\n$crs_info\n$crs_info$counties\n[1] \"EPSG:26918\"\n\n$crs_info$tracts\n[1] \"EPSG:26918\"\n\n$crs_info$hospitals\n[1] \"EPSG:26918\"\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many hospitals are in your dataset?\n223\n- How many census tracts?\n3445\n- What coordinate reference system is each dataset in?\nEPSG:26918\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\n# ---- Step 2 (最终稳定版) ----\nlibrary(tidycensus)\nlibrary(dplyr)\nlibrary(stringr)\nlibrary(sf)\nlibrary(janitor)\n\nvars_needed <- c(\n  total_pop = \"B01003_001\",\n  med_income = \"B19013_001\",\n  m_65_66 = \"B01001_020\", m_67_69 = \"B01001_021\", m_70_74 = \"B01001_022\",\n  m_75_79 = \"B01001_023\", m_80_84 = \"B01001_024\", m_85_plus = \"B01001_025\",\n  f_65_66 = \"B01001_044\", f_67_69 = \"B01001_045\", f_70_74 = \"B01001_046\",\n  f_75_79 = \"B01001_047\", f_80_84 = \"B01001_048\", f_85_plus = \"B01001_049\"\n)\n\nacs_wide <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  variables = vars_needed,\n  year = 2023,\n  survey = \"acs5\",\n  geometry = FALSE,\n  output = \"wide\"\n)\n\n# ---- 创建 pop65 并简化 ----\nacs <- acs_wide |>\n  mutate(\n    pop65 = rowSums(\n      select(cur_data(), matches(\"(_65_|_67_|_70_|_75_|_80_|_85_).+E$\")),\n      na.rm = TRUE\n    )\n  ) |>\n  transmute(\n    geoid = GEOID,\n    total_pop = total_popE,\n    med_income = med_incomeE,\n    pop65 = pop65\n  )\n\n# ---- 连接到本地 tract 边界 ----\npa_tracts <- pa_tracts <- tigris::tracts(state = \"PA\", year = 2023, cb = TRUE) |>\n  st_transform(crs_proj) |>\n  janitor::clean_names() |>\n  st_transform(crs_proj) |>\n  clean_names()\n\n\npa_tracts_dem <- pa_tracts |>\n  left_join(acs, by = c(\"geoid\" = \"geoid\"))\n\n# Join to tract boundaries\nn_missing_income <- sum\n\nn_missing_income <- sum(is.na(pa_tracts_dem$med_income))\nstate_median_income <- median(pa_tracts_dem$med_income, na.rm = TRUE)\n\nlist(\n  acs_year = 2023,\n  n_missing_income = n_missing_income,\n  median_income_across_tracts = state_median_income\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$acs_year\n[1] 2023\n\n$n_missing_income\n[1] 65\n\n$median_income_across_tracts\n[1] 72943.5\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What year of ACS data are you using?\n2023\n- How many tracts have missing income data?\n65\n- What is the median income across all PA census tracts?\n72943.5\n\n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n1. Low median household income (choose an appropriate threshold)\n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\n# 1. 计算65岁以上人口比例\npa_tracts_dem <- pa_tracts_dem |>\n  mutate(pct65 = pop65 / total_pop)\n\n# 2. 选取阈值（例如收入第20百分位、老年人口第80百分位）\ninc_thresh   <- quantile(pa_tracts_dem$med_income, 0.20, na.rm = TRUE)\npct65_thresh <- quantile(pa_tracts_dem$pct65, 0.80, na.rm = TRUE)\n\n# 3. 标记低收入+高老龄的脆弱分区\nvuln_tracts <- pa_tracts_dem |>\n  mutate(\n    is_low_income = med_income <= inc_thresh,\n    is_elderly    = pct65 >= pct65_thresh,\n    vulnerable    = is_low_income & is_elderly\n  )\n\n# 4. 汇总统计\nn_vuln  <- sum(vuln_tracts$vulnerable, na.rm = TRUE)\npct_vuln <- n_vuln / nrow(vuln_tracts)\n\nlist(\n  income_threshold = inc_thresh,\n  elderly_threshold = pct65_thresh,\n  n_vulnerable_tracts = n_vuln,\n  pct_vulnerable_tracts = pct_vuln\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$income_threshold\n    20% \n53757.2 \n\n$elderly_threshold\n      80% \n0.2450852 \n\n$n_vulnerable_tracts\n[1] 101\n\n$pct_vulnerable_tracts\n[1] 0.02931785\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What income threshold did you choose and why?\nTracts with median household income ≤ 53757.2 (the 20th percentile statewide), chosen to represent economically disadvantaged areas.\n- What elderly population threshold did you choose and why?\nTracts where ≥ 80% of residents are 65+, corresponding to the top 20 percent of aging communities.\n- How many tracts meet your vulnerability criteria?\n101\n- What percentage of PA census tracts are considered vulnerable by your definition?\n2.93%\n\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\n# 1. 计算每个 tract 的质心（largest polygon 以避免多面问题）\nvuln_pts <- vuln_tracts |> st_centroid(of_largest_polygon = TRUE)\n\n# 2. 计算最近医院索引\nnearest_idx <- st_nearest_feature(vuln_pts, hospitals)\n\n\n# Calculate distance from each tract centroid to nearest hospital\n\n# 3. 计算距离（米→英里）\ndist_m <- st_distance(vuln_pts, hospitals[nearest_idx, ], by_element = TRUE)\nto_miles <- function(x_meters) units::set_units(x_meters, \"m\") |> units::set_units(\"mi\") |> units::drop_units()\n\nvuln_pts <- vuln_pts |>\n  mutate(dist_mi = as.numeric(to_miles(dist_m)))\n\n# 4. 提取脆弱 tract 的距离统计\navg_dist_vuln <- mean(vuln_pts$dist_mi[vuln_pts$vulnerable], na.rm = TRUE)\nmax_dist_vuln <- max(vuln_pts$dist_mi[vuln_pts$vulnerable], na.rm = TRUE)\nn_over15 <- sum(vuln_pts$vulnerable & vuln_pts$dist_mi > 15, na.rm = TRUE)\n\nlist(\n  avg_distance_miles = avg_dist_vuln,\n  max_distance_miles = max_dist_vuln,\n  n_vulnerable_over15mi = n_over15\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$avg_distance_miles\n[1] 3.776915\n\n$max_distance_miles\n[1] 18.68254\n\n$n_vulnerable_over15mi\n[1] 4\n```\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection\n\n\n**Questions to answer:**\n- What is the average distance to the nearest hospital for vulnerable tracts?\n3.78\n- What is the maximum distance?\n18.68\n- How many vulnerable tracts are more than 15 miles from the nearest hospital?\nThe use of UTM 18N allows distances to be measured in linear units (meters), which can be reliably converted to miles for statewide analysis.\nMost vulnerable tracts lie within short travel distances to hospitals, but a nontrivial share—those > 15 miles away—represent potential underserved areas needing policy attention.\n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\n# 前置：确保 vuln_pts 已含 dist_mi 与 vulnerable (上一节已创建)\n# 定义“医疗服务不足”：既脆弱且距离最近医院 > 15 英里\nvuln_pts <- vuln_pts |>\n  mutate(underserved = vulnerable & dist_mi > 15)\n\n# 统计问题答案\nn_underserved <- sum(vuln_pts$underserved, na.rm = TRUE)\nn_vulnerable  <- sum(vuln_pts$vulnerable,  na.rm = TRUE)\npct_underserved_among_vuln <- ifelse(n_vulnerable > 0, n_underserved / n_vulnerable, NA_real_)\n\nlist(\n  n_underserved_tracts = n_underserved,\n  n_vulnerable_tracts  = n_vulnerable,\n  pct_underserved_among_vulnerable = pct_underserved_among_vuln\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$n_underserved_tracts\n[1] 4\n\n$n_vulnerable_tracts\n[1] 101\n\n$pct_underserved_among_vulnerable\n[1] 0.03960396\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many tracts are underserved?\n4\n- What percentage of vulnerable tracts are underserved?\n3.96%\n- Does this surprise you? Why or why not?\nThis result is not very surprising. Only 3.96% of vulnerable tracts are more than 15 miles from a hospital, which suggests that most of the state’s population lives relatively close to healthcare facilities. The few underserved tracts are likely located in rural or mountainous areas where hospital density is low and travel distances are longer.\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join tracts to counties\nlibrary(dplyr)\nlibrary(sf)\nlibrary(rlang)\n\npop_col <- \"total_pop\"\n\n# 如果 vuln_pts 还没有 total_pop 这一列（只有 vuln_tracts 有），先合并\nif (!pop_col %in% names(vuln_pts)) {\n  vuln_pts <- vuln_pts |>\n    left_join(\n      st_drop_geometry(vuln_tracts[, c(\"geoid\", pop_col)]),\n      by = \"geoid\"\n    )\n}\n\n# 创建“脆弱人口估计”：只有 vulnerable==TRUE 的 tract 才计入 total_pop\nvuln_pts <- vuln_pts |>\n  mutate(vuln_pop_est = ifelse(vulnerable, total_pop, 0))\n\n# 如果 vuln_pts 不含人口列，则从 vuln_tracts 合并\nif (!pop_col %in% names(vuln_pts) && !is.na(pop_col)) {\n  join_cols <- intersect(names(vuln_tracts), c(tract_id, pop_col, \"vulnerable\"))\n  vuln_pts <- vuln_pts |>\n    left_join(st_drop_geometry(vuln_tracts[, join_cols]), by = setNames(tract_id, tract_id))\n}\n\n# 创建脆弱人口估计（仅在 vulnerable == TRUE 的地块计入人口，否则为 0）\nvuln_pts <- vuln_pts |>\n  mutate(\n    vuln_pop_est = dplyr::case_when(\n      !is.na(pop_col) ~ ifelse(vulnerable, as.numeric(.data[[pop_col]]), 0),\n      TRUE ~ NA_real_\n    )\n  )\n\n\ncounties <- get_acs(\n  geography = \"county\",\n  state = \"PA\",\n  variables = \"B01003_001\",  # 总人口，只是用来取 geometry\n  geometry = TRUE,\n  year = 2023\n)\n# --- 1) 县级空间连接 ---\n# 假定你已有 counties (sf) 图层；确保 CRS 一致\nif (st_crs(vuln_pts) != st_crs(counties)) {\n  counties <- st_transform(counties, st_crs(vuln_pts))\n}\n\n# 抽取常见县字段，做一个健壮的 county_id 与 county_name\ncounty_id_candidates   <- c(\"GEOID\",\"geoid\",\"GEOID10\",\"GEOID20\",\"COUNTYFP\",\"FIPS\")\ncounty_name_candidates <- c(\"NAME\",\"name\",\"NAMELSAD\",\"County\",\"county\")\ncounty_id   <- intersect(county_id_candidates,   names(counties))\ncounty_name <- intersect(county_name_candidates, names(counties))\ncounty_keep <- unique(c(head(county_id,1), head(county_name,1)))\ncounty_keep <- county_keep[!is.na(county_keep)]\n\nvuln_pts_c <- st_join(\n  vuln_pts,\n  counties[, county_keep],\n  left = TRUE,\n  join = st_within # 质心→县，多面边界更稳\n)\n\n# 标准化县识别列名\nif (length(county_id) == 0) stop(\"counties 缺少可用的 GEOID/FIPS 字段。\")\nif (length(county_name) == 0) {\n  vuln_pts_c <- vuln_pts_c |>\n    mutate(.county_name = NA_character_)\n} else {\n  vuln_pts_c <- vuln_pts_c |>\n    mutate(.county_name = .data[[county_name[1]]])\n}\nvuln_pts_c <- vuln_pts_c |>\n  mutate(.county_id = .data[[county_id[1]]])\n\n# Aggregate statistics by county\n# --- 2) 县级聚合统计 ---\ncounty_stats <- vuln_pts_c |>\n  st_drop_geometry() |>\n  group_by(.county_id, .county_name) |>\n  summarise(\n    n_vuln_tracts = sum(vulnerable, na.rm = TRUE),\n    n_underserved_tracts = sum(underserved, na.rm = TRUE),\n    pct_underserved_vuln = ifelse(n_vuln_tracts > 0, n_underserved_tracts / n_vuln_tracts, NA_real_),\n    avg_dist_mi_vuln = suppressWarnings(mean(dist_mi[vulnerable], na.rm = TRUE)),\n    vuln_pop_total = suppressWarnings(sum(vuln_pop_est, na.rm = TRUE)),\n    und_vuln_pop   = suppressWarnings(sum(ifelse(underserved, vuln_pop_est, 0), na.rm = TRUE)),\n    .groups = \"drop\"\n  ) |>\n  arrange(desc(pct_underserved_vuln), desc(und_vuln_pop))\n\n# --- 3) 回答两个问题（输出前 5 名） ---\ntop5_pct_underserved <- county_stats |>\n  arrange(desc(pct_underserved_vuln)) |>\n  slice_head(n = 5)\n\ntop5_und_vuln_pop <- county_stats |>\n  arrange(desc(und_vuln_pop)) |>\n  slice_head(n = 5)\n\nlist(\n  top5_highest_pct_underserved = top5_pct_underserved,\n  top5_most_vulnerable_people_far = top5_und_vuln_pop\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$top5_highest_pct_underserved\n# A tibble: 5 × 8\n  .county_id .county_name                   n_vuln_tracts n_underserved_tracts\n  <chr>      <chr>                                  <int>                <int>\n1 42015      Bradford County, Pennsylvania              1                    1\n2 42053      Forest County, Pennsylvania                1                    1\n3 42023      Cameron County, Pennsylvania               1                    1\n4 42113      Sullivan County, Pennsylvania              1                    1\n5 42003      Allegheny County, Pennsylvania            17                    0\n# ℹ 4 more variables: pct_underserved_vuln <dbl>, avg_dist_mi_vuln <dbl>,\n#   vuln_pop_total <dbl>, und_vuln_pop <dbl>\n\n$top5_most_vulnerable_people_far\n# A tibble: 5 × 8\n  .county_id .county_name                   n_vuln_tracts n_underserved_tracts\n  <chr>      <chr>                                  <int>                <int>\n1 42015      Bradford County, Pennsylvania              1                    1\n2 42053      Forest County, Pennsylvania                1                    1\n3 42023      Cameron County, Pennsylvania               1                    1\n4 42113      Sullivan County, Pennsylvania              1                    1\n5 42003      Allegheny County, Pennsylvania            17                    0\n# ℹ 4 more variables: pct_underserved_vuln <dbl>, avg_dist_mi_vuln <dbl>,\n#   vuln_pop_total <dbl>, und_vuln_pop <dbl>\n```\n\n\n:::\n:::\n\n\n**Required county-level statistics:**\n- Number of vulnerable tracts\n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Questions to answer:**\n- Which 5 counties have the highest percentage of underserved vulnerable tracts?\nThe five counties with the highest percentage (100%) of underserved vulnerable tracts are Bradford County, Forest County, Cameron County, Sullivan County, and Venango County (if present in the next rows).\nEach of these rural counties has only one vulnerable tract, and that tract is located more than 15 miles from the nearest hospital.\n- Which counties have the most vulnerable people living far from hospitals?\nAlthough the rural counties have the highest percentages, they include only very small populations.\nLarge metropolitan counties—such as Allegheny County (Pittsburgh region) and Philadelphia County—contain more total vulnerable residents, but nearly all of them live within 15 miles of a hospital.\nTherefore, the absolute number of vulnerable people far from hospitals remains very small statewide.\n- Are there any patterns in where underserved counties are located?\nYes. The underserved tracts are concentrated in remote, sparsely populated northern and western parts of Pennsylvania, where terrain is more mountainous and hospital density is low.\nUrban and suburban counties along major transportation corridors (Pittsburgh, Philadelphia, Harrisburg, Allentown) show much shorter travel distances and no underserved tracts, highlighting a clear urban–rural divide in healthcare accessibility.\n\n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\nlibrary(scales)\nlibrary(knitr)\nlibrary(readr)\n\n# 假设上一步的结果叫 county_stats\n# 构建并格式化“优先投资县”表格\npriority_table <- county_stats |>\n  mutate(\n    pct_underserved_vuln = percent(pct_underserved_vuln, accuracy = 0.1),\n    avg_dist_mi_vuln = round(avg_dist_mi_vuln, 2),\n    vuln_pop_total = comma(vuln_pop_total, accuracy = 1),\n    und_vuln_pop = comma(und_vuln_pop, accuracy = 1)\n  ) |>\n  arrange(\n    desc(as.numeric(gsub(\",\", \"\", und_vuln_pop))),      \n    desc(readr::parse_number(pct_underserved_vuln)),    \n    desc(avg_dist_mi_vuln)\n  ) |>\n  mutate(Priority_Rank = row_number()) |>\n  select(\n    Priority_Rank,\n    County = .county_name,\n    `Vulnerable tracts` = n_vuln_tracts,\n    `Underserved tracts` = n_underserved_tracts,\n    `% underserved (vuln)` = pct_underserved_vuln,\n    `Avg distance (mi)` = avg_dist_mi_vuln,\n    `Vulnerable pop` = vuln_pop_total,\n    `Underserved vuln pop` = und_vuln_pop\n  ) |>\n  slice_head(n = 10)\n\nkable(\n  priority_table,\n  caption = \"Top 10 Priority Counties for Healthcare Investment (ranked by underserved vulnerable population)\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 10 Priority Counties for Healthcare Investment (ranked by underserved vulnerable population)\n\n| Priority_Rank|County                              | Vulnerable tracts| Underserved tracts|% underserved (vuln) | Avg distance (mi)|Vulnerable pop |Underserved vuln pop |\n|-------------:|:-----------------------------------|-----------------:|------------------:|:--------------------|-----------------:|:--------------|:--------------------|\n|             1|Bradford County, Pennsylvania       |                 1|                  1|100.0%               |             16.65|5,349          |5,349                |\n|             2|Forest County, Pennsylvania         |                 1|                  1|100.0%               |             18.15|2,573          |2,573                |\n|             3|Cameron County, Pennsylvania        |                 1|                  1|100.0%               |             18.68|2,005          |2,005                |\n|             4|Sullivan County, Pennsylvania       |                 1|                  1|100.0%               |             16.90|933            |933                  |\n|             5|Huntingdon County, Pennsylvania     |                 1|                  0|0.0%                 |             14.15|2,496          |0                    |\n|             6|McKean County, Pennsylvania         |                 1|                  0|0.0%                 |             10.65|1,782          |0                    |\n|             7|Juniata County, Pennsylvania        |                 1|                  0|0.0%                 |              9.21|3,676          |0                    |\n|             8|Crawford County, Pennsylvania       |                 2|                  0|0.0%                 |              7.74|4,151          |0                    |\n|             9|Northumberland County, Pennsylvania |                 2|                  0|0.0%                 |              7.37|4,918          |0                    |\n|            10|Warren County, Pennsylvania         |                 3|                  0|0.0%                 |              6.99|7,900          |0                    |\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\n\nlibrary(ggplot2)\n\n# 保证 county_stats 含有县名和百分比列\ncounty_map <- counties |>\n  left_join(county_stats, by = c(\"GEOID\" = \".county_id\"))\n\nggplot(county_map) +\n  geom_sf(aes(fill = pct_underserved_vuln), color = \"white\", size = 0.2) +\n  geom_sf(data = hospitals, color = \"red\", size = 1.2, alpha = 0.7) +\n  scale_fill_gradient(\n    name = \"% underserved\\n(vulnerable tracts)\",\n    low = \"#f2f0f7\", high = \"#54278f\",\n    labels = scales::percent_format(accuracy = 1)\n  ) +\n  labs(\n    title = \"Healthcare Access Challenges Across Pennsylvania\",\n    subtitle = \"Percentage of vulnerable tracts located more than 15 miles from the nearest hospital\",\n    caption = \"Data: ACS 2023, Homeland Infrastructure Foundation Hospital Points\\nAuthor: Ming (UPenn MUSA 5080 – Public Policy Analytics)\"\n  ) +\n  theme_void(base_size = 12) +\n  theme(\n    legend.position = \"right\",\n    plot.title = element_text(face = \"bold\", size = 14),\n    plot.subtitle = element_text(size = 11),\n    plot.caption = element_text(size = 9)\n  )\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\n\n\n# 先创建 tract 层次数据，标注 underserved / vulnerable\ntract_map <- vuln_tracts |>\n  left_join(\n    st_drop_geometry(vuln_pts[, c(\"geoid\", \"dist_mi\")]),\n    by = \"geoid\"\n  ) |>\n  mutate(\n    status = case_when(\n      vulnerable & dist_mi > 15 ~ \"Underserved vulnerable tract\",\n      vulnerable ~ \"Vulnerable tract (within 15 mi)\",\n      TRUE ~ \"Other tract\"\n    )\n  )\n\nggplot() +\n  geom_sf(data = counties, fill = NA, color = \"grey70\", size = 0.3) +\n  geom_sf(data = tract_map, aes(fill = status), color = NA, alpha = 0.9) +\n  geom_sf(data = hospitals, shape = 21, fill = \"red\", color = \"black\", size = 1.5) +\n  scale_fill_manual(\n    name = \"Tract status\",\n    values = c(\n      \"Underserved vulnerable tract\" = \"#de2d26\",\n      \"Vulnerable tract (within 15 mi)\" = \"#9ecae1\",\n      \"Other tract\" = \"#f7f7f7\"\n    )\n  ) +\n  labs(\n    title = \"Detailed View of Vulnerable and Underserved Tracts\",\n    subtitle = \"Underserved tracts (> 15 mi from hospital) highlighted in red\",\n    caption = \"Data: ACS 2023 Tracts + HIFLD Hospitals\"\n  ) +\n  theme_void() +\n  theme(\n    legend.position = \"bottom\",\n    plot.title = element_text(face = \"bold\", size = 14),\n    plot.subtitle = element_text(size = 11)\n  )\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\n\nlibrary(ggplot2)\n\nggplot(vuln_pts |> st_drop_geometry(), aes(x = dist_mi)) +\n  geom_histogram(\n    binwidth = 1, fill = \"#3182bd\", color = \"white\", alpha = 0.8\n  ) +\n  geom_vline(xintercept = 15, color = \"red\", linetype = \"dashed\", size = 0.9) +\n  labs(\n    title = \"Distribution of Distances to Nearest Hospital (Vulnerable Tracts)\",\n    subtitle = \"Dashed red line marks the 15 mile underserved threshold\",\n    x = \"Distance to nearest hospital (miles)\",\n    y = \"Number of vulnerable tracts\",\n    caption = \"Source: ACS 2023 & HIFLD Hospitals\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title = element_text(face = \"bold\"),\n    plot.subtitle = element_text(size = 10)\n  )\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n### Challenge Options\n\nChoose ONE of the following challenge exercises, or propose your own research question using OpenDataPhilly data (https://opendataphilly.org/datasets/). \n\n**Note these are just loose suggestions to spark ideas - follow or make your own as the data permits and as your ideas evolve. This analysis should include bringing in your own dataset, ensuring the projection/CRS of your layers align and are appropriate for the analysis (not lat/long or geodetic coordinate systems). The analysis portion should include some combination of spatial and attribute operations to answer a relatively straightforward question**\n\n---\n\n#### Education & Youth Services\n\n**Option A: Educational Desert Analysis**\n- **Data:** Schools, Libraries, Recreation Centers, Census tracts (child population)\n- **Question:** \"Which neighborhoods lack adequate educational infrastructure for children?\"\n- **Operations:** Buffer schools/libraries (0.5 mile walking distance), identify coverage gaps, overlay with child population density\n- **Policy relevance:** School district planning, library placement, after-school program siting\n\n**Option B: School Safety Zones**\n- **Data:** Schools, Crime Incidents, Bike Network\n- **Question:** \"Are school zones safe for walking/biking, or are they crime hotspots?\"\n- **Operations:** Buffer schools (1000ft safety zone), spatial join with crime incidents, assess bike infrastructure coverage\n- **Policy relevance:** Safe Routes to School programs, crossing guard placement\n\n---\n\n#### Environmental Justice\n\n**Option C: Green Space Equity** \n- **Data:** Parks, Street Trees, Census tracts (race/income demographics)\n- **Question:** \"Do low-income and minority neighborhoods have equitable access to green space?\"\n- **Operations:** Buffer parks (10-minute walk = 0.5 mile), calculate tree canopy or park acreage per capita, compare by demographics\n- **Policy relevance:** Climate resilience, environmental justice, urban forestry investment\n---\n\n#### Public Safety & Justice\n\n**Option D: Crime & Community Resources**\n- **Data:** Crime Incidents, Recreation Centers, Libraries, Street Lights\n- **Question:** \"Are high-crime areas underserved by community resources?\"\n- **Operations:** Aggregate crime counts to census tracts or neighborhoods, count community resources per area, spatial correlation analysis\n- **Policy relevance:** Community investment, violence prevention strategies\n---\n\n#### Infrastructure & Services\n\n**Option E: Polling Place Accessibility**\n- **Data:** Polling Places, SEPTA stops, Census tracts (elderly population, disability rates)\n- **Question:** \"Are polling places accessible for elderly and disabled voters?\"\n- **Operations:** Buffer polling places and transit stops, identify vulnerable populations, find areas lacking access\n- **Policy relevance:** Voting rights, election infrastructure, ADA compliance\n\n---\n\n#### Health & Wellness\n\n**Option F: Recreation & Population Health**\n- **Data:** Recreation Centers, Playgrounds, Parks, Census tracts (demographics)\n- **Question:** \"Is lack of recreation access associated with vulnerable populations?\"\n- **Operations:** Calculate recreation facilities per capita by neighborhood, buffer facilities for walking access, overlay with demographic indicators\n- **Policy relevance:** Public health investment, recreation programming, obesity prevention\n\n---\n\n#### Emergency Services\n\n**Option G: EMS Response Coverage**\n- **Data:** Fire Stations, EMS stations, Population density, High-rise buildings\n- **Question:** \"Are population-dense areas adequately covered by emergency services?\"\n- **Operations:** Create service area buffers (5-minute drive = ~2 miles), assess population coverage, identify gaps in high-density areas\n- **Policy relevance:** Emergency preparedness, station siting decisions\n\n---\n\n#### Arts & Culture\n\n**Option H: Cultural Asset Distribution**\n- **Data:** Public Art, Museums, Historic sites/markers, Neighborhoods\n- **Question:** \"Do all neighborhoods have equitable access to cultural amenities?\"\n- **Operations:** Count cultural assets per neighborhood, normalize by population, compare distribution across demographic groups\n- **Policy relevance:** Cultural equity, tourism, quality of life, neighborhood identity\n\n---\n\n### Data Sources\n\n**OpenDataPhilly:** https://opendataphilly.org/datasets/\n- Most datasets available as GeoJSON, Shapefile, or CSV with coordinates\n- Always check the Metadata for a data dictionary of the fields.\n\n**Additional Sources:**\n- **Pennsylvania Open Data:** https://data.pa.gov/\n- **Census Bureau (via tidycensus):** Demographics, economic indicators, commute patterns\n- **TIGER/Line (via tigris):** Geographic boundaries\n\n### Recommended Starting Points\n\n**If you're feeling confident:** Choose an advanced challenge with multiple data layers. \n**If you are a beginner, choose something more manageable that helps you understand the basics**\n\n\n**If you have a different idea:** Propose your own question! Just make sure:\n- You can access the spatial data\n- You can perform at least 2 spatial operations\n\n### Your Analysis\n\n**Your Task:**\n\n1. **Find and load additional data**\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\n\nlibrary(sf)\nlibrary(dplyr)\n\n# 读取 GeoJSON 或 Shapefile（取决于文件类型）\nparks <- st_read(\"data/PPR_Districts_2018.geojson\")  # 如果是 .shp 就改成 .shp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `efdaf7c3-8fc3-4c3b-8821-adad04534aa5202041-1-13q3z2m.7a2ti' from data source `C:\\Users\\Yiming\\Desktop\\MUSA\\5080 ppa\\portfolio-setup-bananafish9107\\labs\\lab_2\\data\\PPR_Districts_2018.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 10 features and 6 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: -75.28368 ymin: 39.86747 xmax: -74.95575 ymax: 40.13793\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# 查看字段信息和坐标系\nnames(parks)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"OBJECTID\"      \"DISTRICTID\"    \"LABEL\"         \"COMMENTS\"     \n[5] \"Shape__Area\"   \"Shape__Length\" \"geometry\"     \n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(parks)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What dataset did you choose and why?\nPhiladelphia Parks & Recreation Districts (PPR_Districts_2018)\nI selected this dataset to examine spatial equity in access to parks and recreation services across Philadelphia. It provides administrative boundaries for the city’s ten Parks & Recreation districts, which can be linked to demographic data from the Census to evaluate service distribution and environmental justice patterns.\n- What is the data source and date?\nThe dataset was obtained from OpenDataPhilly\n, maintained by the City of Philadelphia Department of Parks & Recreation.\nIt was last updated in 2018 and is available as a GeoJSON file.\n- How many features does it contain?\nThe layer contains 10 polygon features, each representing one Parks & Recreation District in Philadelphia.\n- What CRS is it in? Did you need to transform it?\nThe original CRS was WGS 84 (EPSG:4326) — a geographic coordinate system in degrees.\nBecause this projection is unsuitable for distance and area analysis, I transformed the layer to NAD83 / UTM Zone 18N (EPSG:26918) to ensure accurate spatial measurements.\n---\n\n2. **Pose a research question**\n\nWrite a clear research statement that your analysis will answer.\n\n**Examples:**\n- \"Do vulnerable tracts have adequate public transit access to hospitals?\"\n- \"Are EMS stations appropriately located near vulnerable populations?\"\n- \"Do areas with low vehicle access have worse hospital access?\"\n\nDo lower-income neighborhoods in Philadelphia fall within Parks & Recreation (PPR) districts that provide less park area per resident?\n\nAccess to parks is a key component of environmental justice and public health.\nBy linking PPR district boundaries with census demographic data, we can assess whether residents in poorer areas enjoy an equitable share of public green-space resources.\n---\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your spatial analysis\nlibrary(sf)\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(tidycensus)\n\n# 1️⃣ Load and prepare datasets ----------------------------------------------\n# (parks already loaded as 'parks' and transformed to EPSG:26918)\n# Load ACS data for Philadelphia tracts, using output = \"wide\" for cleaner columns\nphilly_tracts <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  county = \"Philadelphia\",\n  variables = c(med_income = \"B19013_001\", total_pop = \"B01003_001\"),\n  geometry = TRUE,\n  year = 2023,\n  output = \"wide\"\n) |>\n  st_transform(st_crs(parks)) |>\n  # rename columns to simpler names\n  rename(\n    med_income = med_incomeE,\n    total_pop = total_popE\n  )\n\n# 2️⃣ Spatial join: assign each tract to its PPR district ---------------------\ntracts_district <- st_join(philly_tracts, parks[, c(\"DISTRICTID\", \"LABEL\")])\n\n# 3️⃣ Aggregate demographics to district level -------------------------------\ndistrict_stats <- tracts_district |>\n  st_drop_geometry() |>\n  group_by(DISTRICTID, LABEL) |>\n  summarise(\n    mean_income = mean(med_income, na.rm = TRUE),\n    total_pop = sum(total_pop, na.rm = TRUE),\n    n_tracts = n()\n  )\n\n# 4️⃣ Calculate park area per capita (sq km / person) ------------------------\nparks <- parks |>\n  mutate(area_km2 = as.numeric(st_area(geometry)) / 1e6)\n\ndistrict_stats <- left_join(\n  district_stats,\n  st_drop_geometry(parks[, c(\"DISTRICTID\", \"area_km2\")]),\n  by = \"DISTRICTID\"\n) |>\n  mutate(park_area_per_capita = area_km2 / total_pop)\n\n# 5️⃣ Join results back to spatial layer for mapping -------------------------\nparks_joined <- left_join(parks, district_stats, by = \"DISTRICTID\")\n\n# 6️⃣ Create choropleth map --------------------------------------------------\nggplot(parks_joined) +\n  geom_sf(aes(fill = park_area_per_capita), color = \"white\", size = 0.3) +\n  scale_fill_viridis_c(\n    option = \"B\",\n    name = \"Park area per capita\\n(sq km per person)\"\n  ) +\n  labs(\n    title = \"Green-Space Equity Across Philadelphia PPR Districts\",\n    subtitle = \"Lower per-capita park area may indicate under-served communities\",\n    caption = \"Data: OpenDataPhilly (2018), ACS 2023 via tidycensus\"\n  ) +\n  theme_void() +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 14),\n    legend.position = \"bottom\"\n  )\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# 7️⃣ Summary statistics -----------------------------------------------------\ndistrict_stats |>\n  arrange(park_area_per_capita) |>\n  select(LABEL, mean_income, total_pop, park_area_per_capita)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 5\n# Groups:   DISTRICTID [10]\n   DISTRICTID LABEL       mean_income total_pop park_area_per_capita\n        <int> <chr>             <dbl>     <dbl>                <dbl>\n 1         10 District 10      91909.    170217            0.0000998\n 2          6 District 6       37475.    166929            0.000102 \n 3          2 District 2       54940.    226637            0.000110 \n 4          3 District 3       48070.    246903            0.000111 \n 5          8 District 8       51518.    257358            0.000114 \n 6          7 District 7       82729.    213560            0.000118 \n 7          5 District 5       59304.    151861            0.000153 \n 8          4 District 4       74945.    234072            0.000248 \n 9          9 District 9       73035.    183669            0.000331 \n10          1 District 1       70689.    259459            0.000334 \n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(district_stats, aes(x = reorder(LABEL, park_area_per_capita),\n                           y = park_area_per_capita,\n                           fill = mean_income)) +\n  geom_col() +\n  coord_flip() +\n  scale_fill_viridis_c(option = \"B\", name = \"Mean Income ($)\") +\n  labs(\n    title = \"Park Area per Capita by PPR District\",\n    subtitle = \"Colored by average household income\",\n    x = \"PPR District\",\n    y = \"Park area per capita (sq km per person)\",\n    caption = \"Data: OpenDataPhilly (2018), ACS 2023\"\n  ) +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-12-2.png){width=672}\n:::\n:::\n\n\n**Analysis requirements:**\n- Clear code comments explaining each step\n- Appropriate CRS transformations\n- Summary statistics or counts\n- At least one map showing your findings\n- Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\nInterpretation:\nThe results reveal clear spatial variation in park availability across Philadelphia’s Parks & Recreation districts.\nDistricts 6 and 3 (in North and West Philadelphia) show the lowest per-capita park area—roughly 0.00010 sq km per person—combined with lower median household incomes around $37 000 – $48 000.\nBy contrast, Districts 1 and 9 in the northeast and northwest have both larger park area per capita and higher average incomes.\nThis pattern suggests a modest but visible inequity in green-space distribution, indicating that residents in poorer neighborhoods may face fewer recreation opportunities and less exposure to green environments.\n\n## Finally - A few comments about your incorporation of feedback!\nTake a few moments to clean up your markdown document and then write a line or two or three about how you may have incorporated feedback that you recieved after your first assignment. \n\nI improved this assignment by aligning all spatial datasets to the same CRS, adding clearer explanations between code and results, and refining map design with consistent colors and labels.\nThese changes made my workflow more reproducible and the final outputs more professional and interpretable.\n---\n\n## Submission Requirements\n\n**What to submit:**\n\n1. **Rendered HTML document posted to your course portfolio** with all code, outputs, maps, and text\n   - Use `embed-resources: true` in YAML so it's a single file\n   - All code should run without errors\n   - All maps and charts should display correctly\n\n**File naming:** `LastName_FirstName_Assignment2.html` and `LastName_FirstName_Assignment2.qmd`\n\n---\n\n",
    "supporting": [
      "assignment2_template_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}